// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package blockchain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	"time"
	"github.com/elon0823/paust-db/util"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Index                int32    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Timestamp            uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BPM                  int32    `protobuf:"varint,3,opt,name=BPM,proto3" json:"BPM,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PrevHash             string   `protobuf:"bytes,5,opt,name=PrevHash,proto3" json:"PrevHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetBPM() int32 {
	if m != nil {
		return m.BPM
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (block *Block) CalculateHash() string {

	return util.CalculateHash(strconv.FormatInt(int64(block.Index), 10), 
		strconv.FormatUint(block.Timestamp, 10), strconv.FormatInt(int64(block.BPM), 10), 
		block.PrevHash)
}

func Genesis() (*Block) {
	return NewBlock(0, 0, "")
}

func NewBlock(index int32, bpm int32, prevHash string) (*Block) {

	block := Block{
		Index: index,
		Timestamp: uint64(time.Now().UnixNano()),
		BPM: bpm,
		Hash: "",
		PrevHash: prevHash,
	}
	block.Hash = block.CalculateHash()

	return &block
}

func init() {
	proto.RegisterType((*Block)(nil), "blockchain.Block")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xc9, 0x4f,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x73, 0x92, 0x33, 0x12, 0x33, 0xf3,
	0x94, 0x6a, 0xb9, 0x58, 0x9d, 0x40, 0x3c, 0x21, 0x11, 0x2e, 0x56, 0xcf, 0xbc, 0x94, 0xd4, 0x0a,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x08, 0x47, 0x48, 0x86, 0x8b, 0xb3, 0x24, 0x33, 0x37,
	0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x40, 0x82, 0x49, 0x81, 0x51, 0x83, 0x25, 0x08, 0x21, 0x20, 0x24,
	0xc0, 0xc5, 0xec, 0x14, 0xe0, 0x2b, 0xc1, 0x0c, 0xd6, 0x01, 0x62, 0x0a, 0x09, 0x71, 0xb1, 0x78,
	0x24, 0x16, 0x67, 0x48, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x52, 0x5c, 0x1c,
	0x01, 0x45, 0xa9, 0x65, 0x60, 0x71, 0x56, 0xb0, 0x38, 0x9c, 0x9f, 0xc4, 0x06, 0x76, 0x91, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xec, 0x9b, 0x1e, 0xa0, 0x00, 0x00, 0x00,
}
